name: Run on commit
on: 
  push: 
    branches: 
      - main
jobs: 
  commit-details:
    runs-on: ubuntu-latest
    steps: 
      - name: Get commit message
        run: echo "Latest commit message = ${{github.event.head_commit.message}} "
